import { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: "clothing",
    name: "Clothing",
    slug: "clothing",
    icon: "👗",
    description: "Handwoven sarees, kurtas, and traditional wear",
    productCount: 3,
  },
  {
    id: "jewelry",
    name: "Jewelry",
    slug: "jewelry",
    icon: "💍",
    description: "Handcrafted silver, gold, and beaded jewelry",
    productCount: 3,
  },
  {
    id: "home-kitchen",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    icon: "🏺",
    description: "Artisan pottery, brass, and woodwork",
    productCount: 2,
  },
  {
    id: "beauty",
    name: "Beauty",
    slug: "beauty",
    icon: "🌿",
    description: "Natural, Ayurvedic beauty and wellness",
    productCount: 2,
  },
  {
    id: "handicrafts",
    name: "Handicrafts",
    slug: "handicrafts",
    icon: "🎨",
    description: "Paintings, sculptures, and handmade art",
    productCount: 2,
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Banarasi Silk Saree in Crimson & Gold",
    slug: "banarasi-silk-saree-crimson-gold",
    category: "Clothing",
    categorySlug: "clothing",
    price: 4800,
    originalPrice: 6500,
    rating: 4.8,
    reviewCount: 124,
    stock: 8,
    images: [
      "https://picsum.photos/seed/banarasi-saree-a/800/800",
      "https://picsum.photos/seed/banarasi-saree-b/800/800",
      "https://picsum.photos/seed/banarasi-saree-c/800/800",
    ],
    shortDescription:
      "Exquisite Banarasi silk saree with zari work, handwoven by master weavers in Varanasi.",
    description:
      "This stunning Banarasi silk saree is a masterpiece of traditional Indian craftsmanship. Handwoven by fourth-generation weavers in the ancient city of Varanasi, it features intricate zari brocade work with gold and silver threads. The rich crimson base is adorned with floral motifs and a grand pallu that tells a story of centuries-old artistry. Perfect for weddings, festivals, and special occasions.",
    details: {
      material: "Pure Silk with Zari",
      origin: "Varanasi, Uttar Pradesh",
      dimensions: "5.5 metres + 0.8 metre blouse piece",
      weight: "800g",
      careInstructions: "Dry clean only",
      artisanName: "Ustad Ramesh Ansari",
    },
    tags: ["saree", "silk", "bridal", "festive", "banarasi"],
    artisan: "Ansari Weaves",
    location: "Varanasi, UP",
    featured: true,
    reviews: [
      {
        id: "r1",
        author: "Priya Sharma",
        avatar: "https://picsum.photos/seed/user-priya/80/80",
        rating: 5,
        title: "Absolutely stunning!",
        comment:
          "The saree exceeded my expectations. The silk is incredibly smooth and the zari work is breathtaking. Wore it to my cousin's wedding and received so many compliments.",
        date: "2024-11-15",
        verified: true,
      },
      {
        id: "r2",
        author: "Kavitha Nair",
        avatar: "https://picsum.photos/seed/user-kavitha/80/80",
        rating: 5,
        title: "Heirloom quality",
        comment:
          "This is the kind of saree you pass down through generations. The craftsmanship is impeccable.",
        date: "2024-10-22",
        verified: true,
      },
    ],
  },
  {
    id: "2",
    name: "Phulkari Embroidered Dupatta",
    slug: "phulkari-embroidered-dupatta",
    category: "Clothing",
    categorySlug: "clothing",
    price: 1200,
    originalPrice: 1600,
    rating: 4.6,
    reviewCount: 89,
    stock: 15,
    images: [
      "https://picsum.photos/seed/phulkari-a/800/800",
      "https://picsum.photos/seed/phulkari-b/800/800",
    ],
    shortDescription:
      "Traditional Phulkari embroidery from Punjab on vibrant hand-dyed fabric.",
    description:
      "The Phulkari dupatta is a celebration of Punjab's rich textile heritage. Each piece is hand-embroidered by skilled artisans using silk threads on hand-dyed cotton fabric. The word 'Phulkari' means 'flower work' — a tradition passed down through generations of Punjabi women.",
    details: {
      material: "Cotton with Silk Thread Embroidery",
      origin: "Patiala, Punjab",
      dimensions: "2.5 metres",
      weight: "200g",
      careInstructions: "Hand wash in cold water",
      artisanName: "Gurpreet Kaur",
    },
    tags: ["dupatta", "embroidery", "phulkari", "punjabi", "cotton"],
    artisan: "Kaur Crafts",
    location: "Patiala, Punjab",
    featured: true,
    reviews: [
      {
        id: "r3",
        author: "Simran Bedi",
        avatar: "https://picsum.photos/seed/user-simran/80/80",
        rating: 5,
        title: "Beautiful piece of art",
        comment:
          "The embroidery is so detailed and the colors are vibrant. Worth every rupee!",
        date: "2024-12-01",
        verified: true,
      },
    ],
  },
  {
    id: "3",
    name: "Block Print Cotton Kurta Set",
    slug: "block-print-cotton-kurta-set",
    category: "Clothing",
    categorySlug: "clothing",
    price: 1800,
    rating: 4.5,
    reviewCount: 67,
    stock: 22,
    images: ["https://picsum.photos/seed/kurta-block-a/800/800"],
    shortDescription: "Jaipur block-printed cotton kurta with palazzo pants.",
    description:
      "This elegant kurta set is made from 100% handspun cotton, hand-printed using traditional wooden blocks carved in Jaipur. Each block is hand-carved, ensuring no two pieces are identical. The natural indigo and rust dyes are sourced from plants, making this an eco-friendly fashion choice.",
    details: {
      material: "Handspun Cotton",
      origin: "Jaipur, Rajasthan",
      dimensions: "S, M, L, XL, XXL",
      careInstructions: "Gentle machine wash, do not bleach",
      artisanName: "Champa Devi",
    },
    tags: ["kurta", "block-print", "cotton", "jaipur", "sustainable"],
    artisan: "Rangrez Collective",
    location: "Jaipur, Rajasthan",
    featured: false,
    reviews: [],
  },
  {
    id: "4",
    name: "Oxidised Silver Jhumka Earrings",
    slug: "oxidised-silver-jhumka-earrings",
    category: "Jewelry",
    categorySlug: "jewelry",
    price: 850,
    rating: 4.9,
    reviewCount: 203,
    stock: 30,
    images: [
      "https://picsum.photos/seed/jhumka-a/800/800",
      "https://picsum.photos/seed/jhumka-b/800/800",
    ],
    shortDescription:
      "Handcrafted oxidised silver jhumka earrings with intricate filigree work.",
    description:
      "These exquisite jhumka earrings are handcrafted by skilled silversmiths from Rajasthan. Made from 92.5 sterling silver with oxidised finish, they feature traditional bell-shaped design with delicate filigree work and dangling metallic beads. Each pair is unique and takes 3–4 hours to craft.",
    details: {
      material: "92.5 Sterling Silver (Oxidised)",
      origin: "Jaipur, Rajasthan",
      weight: "25g per pair",
      dimensions: "6cm drop",
      careInstructions: "Wipe with dry cloth, store in airtight box",
      artisanName: "Mohammad Iqbal Silversmiths",
    },
    tags: ["earrings", "jhumka", "silver", "oxidised", "traditional"],
    artisan: "Silver Haat",
    location: "Jaipur, Rajasthan",
    featured: true,
    reviews: [
      {
        id: "r4",
        author: "Ananya Roy",
        avatar: "https://picsum.photos/seed/user-ananya/80/80",
        rating: 5,
        title: "Perfect jhumkas!",
        comment:
          "These are exactly what I was looking for. The craftsmanship is amazing and they look stunning.",
        date: "2024-12-10",
        verified: true,
      },
    ],
  },
  {
    id: "5",
    name: "Meenakari Bangles Set of 6",
    slug: "meenakari-bangles-set",
    category: "Jewelry",
    categorySlug: "jewelry",
    price: 1400,
    originalPrice: 1800,
    rating: 4.7,
    reviewCount: 156,
    stock: 18,
    images: [
      "https://picsum.photos/seed/bangles-a/800/800",
      "https://picsum.photos/seed/bangles-b/800/800",
    ],
    shortDescription:
      "Traditional Meenakari enamel work bangles in vibrant colors.",
    description:
      "Meenakari is the ancient art of coloring metal surfaces with vibrant enamel colors. This set of 6 bangles showcases the finest Jaipur Meenakari work — gold-plated brass bangles adorned with intricate floral patterns in vivid enamel colors of red, green, and blue. A stunning accessory for festive occasions.",
    details: {
      material: "Gold-plated Brass with Enamel",
      origin: "Jaipur, Rajasthan",
      dimensions: "Available in sizes 2.4, 2.6, 2.8",
      weight: "150g (set of 6)",
      careInstructions: "Avoid water contact, wipe with soft cloth",
    },
    tags: ["bangles", "meenakari", "enamel", "gold-plated", "festive"],
    artisan: "Meena Kala Studio",
    location: "Jaipur, Rajasthan",
    featured: false,
    reviews: [],
  },
  {
    id: "6",
    name: "Tribal Dokra Brass Necklace",
    slug: "tribal-dokra-necklace",
    category: "Jewelry",
    categorySlug: "jewelry",
    price: 2200,
    rating: 4.8,
    reviewCount: 78,
    stock: 12,
    images: ["https://picsum.photos/seed/dokra-a/800/800"],
    shortDescription:
      "Ancient Dokra lost-wax cast brass necklace from Bastar tribal artisans.",
    description:
      "Dokra is one of the oldest forms of metal casting. This necklace is made by tribal artisans of Bastar, Chhattisgarh, using the 4000-year-old lost-wax technique. Each piece is unique and tells the story of tribal mythology and nature. The rustic, earthy finish makes it a statement piece.",
    details: {
      material: "Brass (Lost-wax cast)",
      origin: "Bastar, Chhattisgarh",
      weight: "180g",
      dimensions: "45cm chain",
      artisanName: "Tribal Craft Collective",
    },
    tags: ["necklace", "dokra", "tribal", "brass", "bastar"],
    artisan: "Bastar Crafts",
    location: "Bastar, Chhattisgarh",
    featured: true,
    reviews: [],
  },
  {
    id: "7",
    name: "Hand-Painted Terracotta Planter Set",
    slug: "terracotta-planter-set",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    price: 1100,
    rating: 4.5,
    reviewCount: 91,
    stock: 25,
    images: [
      "https://picsum.photos/seed/terracotta-a/800/800",
      "https://picsum.photos/seed/terracotta-b/800/800",
    ],
    shortDescription: "Set of 3 hand-painted terracotta planters with saucers.",
    description:
      "These beautiful terracotta planters are handmade and hand-painted by potters from Khurja. Using natural clay and mineral paints, each pot is unique with traditional Rajasthani patterns. The porous nature of terracotta allows air and moisture exchange, making them perfect for herbs, succulents, and flowering plants.",
    details: {
      material: "Natural Terracotta Clay",
      origin: "Khurja, Uttar Pradesh",
      dimensions: "Small: 10cm, Medium: 15cm, Large: 20cm",
      weight: "1.5kg (set of 3)",
      careInstructions: "Soak in water before first use",
    },
    tags: ["planter", "terracotta", "clay", "hand-painted", "eco-friendly"],
    artisan: "Khurja Pottery",
    location: "Khurja, UP",
    featured: false,
    reviews: [],
  },
  {
    id: "8",
    name: "Engraved Brass Diyas (Set of 5)",
    slug: "brass-diyas-set",
    category: "Home & Kitchen",
    categorySlug: "home-kitchen",
    price: 650,
    rating: 4.7,
    reviewCount: 178,
    stock: 45,
    images: ["https://picsum.photos/seed/diya-a/800/800"],
    shortDescription:
      "Traditional brass diyas with ornate engravings for puja and home decor.",
    description:
      "These elegant brass diyas are handcrafted by skilled artisans from Moradabad, the 'Brass City' of India. Each diya features intricate engravings of traditional motifs — peacocks, lotus flowers, and geometric patterns. Solid brass construction ensures durability and a beautiful golden patina over time.",
    details: {
      material: "Solid Brass",
      origin: "Moradabad, Uttar Pradesh",
      dimensions: "6cm diameter each",
      weight: "500g (set of 5)",
      careInstructions: "Polish with lemon juice and salt to maintain shine",
    },
    tags: ["diya", "brass", "puja", "diwali", "home-decor"],
    artisan: "Moradabad Brass Works",
    location: "Moradabad, UP",
    featured: true,
    reviews: [
      {
        id: "r5",
        author: "Meera Patel",
        avatar: "https://picsum.photos/seed/user-meera/80/80",
        rating: 5,
        title: "Perfect for Diwali",
        comment:
          "Beautiful diyas! The brass quality is excellent and the engravings are very detailed.",
        date: "2024-11-01",
        verified: true,
      },
    ],
  },
  {
    id: "9",
    name: "Rose Water & Sandalwood Face Mist",
    slug: "rose-water-sandalwood-face-mist",
    category: "Beauty",
    categorySlug: "beauty",
    price: 480,
    rating: 4.6,
    reviewCount: 145,
    stock: 60,
    images: ["https://picsum.photos/seed/rose-mist-a/800/800"],
    shortDescription:
      "Pure Ayurvedic rose water and sandalwood face mist, 100% natural.",
    description:
      "This refreshing face mist is formulated using ancient Ayurvedic recipes. Made with steam-distilled Kannauj rose water and pure sandalwood extract, it tones, hydrates, and refreshes skin instantly. Free from alcohol, parabens, and synthetic fragrances. Suitable for all skin types.",
    details: {
      material: "Rose Water, Sandalwood Extract, Glycerin",
      origin: "Kannauj, Uttar Pradesh",
      dimensions: "100ml spray bottle",
      weight: "150g",
      careInstructions: "Store in cool, dry place. Use within 6 months of opening.",
    },
    tags: ["skincare", "ayurvedic", "rose-water", "natural", "face-mist"],
    artisan: "Kannauj Botanicals",
    location: "Kannauj, UP",
    featured: false,
    reviews: [],
  },
  {
    id: "10",
    name: "Kumkumadi Brightening Face Oil",
    slug: "kumkumadi-brightening-face-oil",
    category: "Beauty",
    categorySlug: "beauty",
    price: 1650,
    originalPrice: 2000,
    rating: 4.8,
    reviewCount: 232,
    stock: 35,
    images: ["https://picsum.photos/seed/kumkumadi-a/800/800"],
    shortDescription:
      "Traditional Kumkumadi tailam with 16 precious herbs for skin brightening.",
    description:
      "Kumkumadi Tailam is a centuries-old Ayurvedic formulation. This luxurious face oil blends 16 precious herbs including saffron, sandalwood, and manjistha in a sesame oil base. Regular use brightens skin tone, reduces dark spots, and imparts a natural glow. Cold-pressed and crafted in small batches using traditional Kerala methods.",
    details: {
      material: "Sesame Oil, Saffron, Sandalwood, 14 Ayurvedic herbs",
      origin: "Thrissur, Kerala",
      dimensions: "30ml glass dropper bottle",
      careInstructions:
        "Apply 3–4 drops on face before bedtime. Patch test recommended.",
    },
    tags: ["skincare", "ayurvedic", "kumkumadi", "saffron", "anti-aging"],
    artisan: "Kerala Vaidyam",
    location: "Thrissur, Kerala",
    featured: true,
    reviews: [
      {
        id: "r6",
        author: "Deepa Krishnan",
        avatar: "https://picsum.photos/seed/user-deepa/80/80",
        rating: 5,
        title: "Liquid gold!",
        comment:
          "My skin has never looked better. The saffron smell is divine and I can see a noticeable difference in 2 weeks.",
        date: "2024-12-05",
        verified: true,
      },
    ],
  },
  {
    id: "11",
    name: "Madhubani Painting — The Tree of Life",
    slug: "madhubani-tree-of-life",
    category: "Handicrafts",
    categorySlug: "handicrafts",
    price: 3500,
    rating: 4.9,
    reviewCount: 56,
    stock: 7,
    images: [
      "https://picsum.photos/seed/madhubani-a/800/800",
      "https://picsum.photos/seed/madhubani-b/800/800",
    ],
    shortDescription:
      "Original Madhubani painting on handmade paper, depicting the Tree of Life.",
    description:
      "This original Madhubani painting is created by a National Award-winning artisan from Mithila, Bihar. Madhubani art is a UNESCO-recognized traditional painting style that uses natural dyes. This piece depicts the sacred 'Tree of Life' surrounded by birds, fish, and floral patterns in the characteristic geometric Mithila style. Comes with a certificate of authenticity.",
    details: {
      material: "Natural pigments on handmade paper",
      origin: "Madhubani, Bihar",
      dimensions: "30cm × 45cm",
      weight: "150g",
      artisanName: "Sita Devi",
    },
    tags: ["painting", "madhubani", "mithila", "original", "wall-art"],
    artisan: "Mithila Arts Trust",
    location: "Madhubani, Bihar",
    featured: true,
    reviews: [
      {
        id: "r7",
        author: "Arjun Gupta",
        avatar: "https://picsum.photos/seed/user-arjun/80/80",
        rating: 5,
        title: "Museum quality",
        comment:
          "This is a museum-quality piece. The artisan's skill is extraordinary. The natural colors are vibrant and the composition is breathtaking.",
        date: "2024-11-20",
        verified: true,
      },
    ],
  },
  {
    id: "12",
    name: "Jaipur Blue Pottery Serving Bowl Set",
    slug: "blue-pottery-serving-bowl-set",
    category: "Handicrafts",
    categorySlug: "handicrafts",
    price: 2100,
    originalPrice: 2800,
    rating: 4.6,
    reviewCount: 112,
    stock: 14,
    images: [
      "https://picsum.photos/seed/blue-pottery-a/800/800",
      "https://picsum.photos/seed/blue-pottery-b/800/800",
    ],
    shortDescription:
      "Jaipur Blue Pottery set of 4 bowls with traditional floral motifs.",
    description:
      "Jaipur Blue Pottery is a craft with Persian origins that flourished in Rajasthan. This set of 4 serving bowls features the iconic electric blue and white palette with traditional floral and geometric motifs. Made using quartz stone powder, glass, and kite string, the pottery is lightweight and has a distinctive semi-translucent quality. Food-safe with lead-free glaze.",
    details: {
      material: "Quartz, Glass, Multani Mitti (Lead-free glaze)",
      origin: "Jaipur, Rajasthan",
      dimensions: "15cm diameter each",
      weight: "600g (set of 4)",
      careInstructions: "Hand wash only, not microwave safe",
    },
    tags: ["pottery", "blue-pottery", "jaipur", "serving", "table-decor"],
    artisan: "Jaipur Blue Arts",
    location: "Jaipur, Rajasthan",
    featured: false,
    reviews: [],
  },
];

export const featuredProducts = products.filter((p) => p.featured);
